--Calculate the number of orders and total revenue for each month.
SELECT 
    DATE_TRUNC('month', order_date) AS month,
    COUNT(order_id) AS number_of_orders,
    SUM(total_amount) AS total_revenue
FROM Orders
GROUP BY DATE_TRUNC('month', order_date)
ORDER BY month;



--Identify customers who haven’t made any purchases.
SELECT c.customer_id, c.name
FROM customers c
LEFT JOIN orders o ON c.customer_id = o.customer_id
WHERE o.customer_id IS NULL;



--List the top 5 customers by total spending.
SELECT c.customer_id, c.name, SUM(o.total_amount) AS total_spending
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.name
ORDER BY total_spending DESC
LIMIT 5;


--Calculate the total revenue generated by the e-commerce platform.
SELECT SUM(total_amount) AS total_revenue
FROM orders;
